# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_auto_20161029_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventTypeAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.EventType')),
            ],
        ),
        migrations.CreateModel(
            name='EventTypeAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40)),
                ('event_type_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.EventTypeAttribute')),
            ],
        ),
        migrations.RemoveField(
            model_name='day',
            name='shower_temp',
        ),
        migrations.RemoveField(
            model_name='day',
            name='soap_type',
        ),
        migrations.AddField(
            model_name='eventattribute',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.EventTypeAttributeValue'),
        ),
    ]
