# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 18:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_delete_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattributevalue',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventattributevalue',
            name='value',
        ),
        migrations.RemoveField(
            model_name='eventtypeattribute',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='eventtypeattributevalue',
            name='event_type_attribute',
        ),
        migrations.AddField(
            model_name='event',
            name='attrs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='attr_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='EventAttributeValue',
        ),
        migrations.DeleteModel(
            name='EventTypeAttribute',
        ),
        migrations.DeleteModel(
            name='EventTypeAttributeValue',
        ),
    ]
