---
- hosts: all
  vars:
    home_path: /home/ubuntu
    sneezly_repo_path: "{{ home_path }}/sneezly"
    sneezly_app_path: "{{ sneezly_repo_path }}/sneezly"
    sneezly_env_path: "{{ home_path }}/venvs/sneezly_env"
    database_name: sneezly
    database_username: ejm
  remote_user: ubuntu
  tasks:
  - name: Include secret variables
    include_vars:
      file: secrets.yml
      name: secrets
  - name: Install system packages
    apt:
      name: "{{item}}"
      state: installed
    with_items:
      - virtualenv
      - redis-server
      - postgresql
      - libpq-dev
      - python-psycopg2
    become: true
  - name: Install list of python packages for system
    pip:
      name: "{{item}}"
      state: latest
      executable: pip2
    with_items:
      - pip
      - psycopg2
      - supervisor
    become: true
  - name: Copy supervisor daemon configuration file
    template:
      src: supervisord.conf
      dest: /etc/
    become: true
  - name: Copy supervisor daemon systemd script
    copy:
      src: supervisord.service
      dest: /etc/systemd/system/
    become: true
  - name: Make sneezly virtualenv
    pip:
      name: pip
      state: latest
      virtualenv: "{{ sneezly_env_path }}"
      virtualenv_python: python3.5
  - name: Clone sneezly repository
    git:
      repo: https://github.com/eddiejessup/sneezly.git
      dest: "{{ sneezly_repo_path }}"
      accept_hostkey: true
  - name: Install list of python packages for sneezly
    pip:
      requirements: "{{ sneezly_app_path }}/requirements.txt"
      executable: /home/ubuntu/venvs/sneezly_env/bin/pip
  - name: Copy sneezly app deployment settings
    template:
      src: settings.ini
      dest: "{{ sneezly_app_path }}/sneezly/"
  - name: Create database
    postgresql_db:
      name: "{{ database_name }}"
    become: true
    become_user: postgres
  - name: Create sneezly database user and grant privileges
    postgresql_user:
      name: "{{ database_username }}"
      password: "{{ secrets['database_password'] }}"
      db: "{{ database_name }}"
      priv: ALL
    become: true
    become_user: postgres
  - name: Run Django migrations
    django_manage:
      command: migrate
      app_path: "{{ sneezly_app_path }}"
      virtualenv: "{{ sneezly_env_path }}"
  - name: Start redis server
    service:
      name: redis-server
      state: started
    become: true
  - name: Start postgresql server
    service:
      name: postgresql
      state: started
    become: true
  - name: Start supervisor daemon
    systemd:
      name: supervisord
      state: started
      daemon_reload: yes
    become: true
