---
- hosts: all
  vars:
    sneezly_repo_path: ~/sneezly
    sneezly_app_path: "{{ sneezly_repo_path }}/sneezly"
    sneezly_env_path: "~/venvs/sneezly_env"
  remote_user: ubuntu
  tasks:
  - name: Include secret variables
    include_vars:
      file: secrets.yml
      name: sneezly
  - name: Install system packages
    apt:
      name: "{{item}}"
      state: installed
    with_items:
      - virtualenv
      - redis-server
      - postgresql
      - libpq-dev
      - python-psycopg2
    become: true
  - name: Install list of python (2) packages for system
    pip:
      name: "{{item}}"
      state: latest
      executable: pip2
    with_items:
      - pip
      - psycopg2
      - supervisor
    become: true
  - name: Copy supervisor daemon configuration file
    copy:
      src: supervisord.conf
      dest: /etc/
    become: true
  - name: Copy supervisor daemon systemd script
    copy:
      src: supervisord.service
      dest: /etc/systemd/system/
    become: true
  - name: Make sneezly virtualenv
    pip:
      name: pip
      state: latest
      virtualenv: "{{ sneezly_env_path }}"
      virtualenv_python: python3.5
  - name: Clone sneezly repository
    git:
      repo: https://github.com/eddiejessup/sneezly.git
      dest: "{{ sneezly_repo_path }}"
      accept_hostkey: true
  - name: Install list of python packages for sneezly
    pip:
      requirements: "{{ sneezly_app_path }}/requirements.txt"
      executable: /home/ubuntu/venvs/sneezly_env/bin/pip
  - name: Copy sneezly app deployment settings
    copy:
      src: settings.ini
      dest: "{{ sneezly_app_path }}/sneezly/"
  - name: Create database
    postgresql_db:
      name: sneezly
    become: true
    become_user: postgres
  - name: Create sneezly database user and grant privileges
    postgresql_user:
      db: sneezly
      name: ejm
      password: sdenton55y
      priv: ALL
    become: true
    become_user: postgres
  - name: Run Django migrations
    django_manage:
      command: migrate
      app_path: "{{ sneezly_app_path }}"
      virtualenv: "{{ sneezly_env_path }}"
  - name: Add to .profile to set Djangobot token environment variable
    lineinfile:
      dest: "~/.profile"
      line: "export DJANGOBOT_TOKEN={{ sneezly['djangobot_token'] }}"
  - name: Start redis server
    service:
      name: redis-server
      state: started
    become: true
  - name: Start postgresql server
    service:
      name: postgresql
      state: started
    become: true
  - name: Start supervisor daemon
    systemd:
      name: supervisord
      state: started
      daemon_reload: yes
    become: true
