# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20161029_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
