# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20161029_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
