# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0010_auto_20161031_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypeAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.EventType')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time_last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
