# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0011_auto_20161107_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'MessageLogEntries',
                'verbose_name': 'MessageLogEntry',
            },
        ),
    ]
