# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0012_messagelogentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagelogentry',
            options={'get_latest_by': 'time_created', 'verbose_name': 'MessageLogEntry', 'verbose_name_plural': 'MessageLogEntries'},
        ),
    ]
